export const DTO_CONSTANTS = {
    QUERY_PAGE_EXAMPLE: 1,
    QUERY_PAGE_SIZE_EXAMPLE: 10,
    QUERY_SORT_BY_EXAMPLE: 'name',
    QUERY_SORT_ORDER_EXAMPLE: 'ASC',
    QUERY_FILTER_BY_EXAMPLE: '{"name":"John"}',
    ID_EXAMPLE_NUMBER: 123,
    ID_EXAMPLE_STRING: '123',
    USER_EMAIL: 'User email',
    USER_EMAIL_EXAMPLE: 'john.doe@example.com',
    USER_PASSWORD: 'User password',
    USER_PASSWORD_EXAMPLE: 'Password@123',
    USER_FIRST_NAME: 'User first name',
    USER_FIRST_NAME_EXAMPLE: 'John',
    USER_LAST_NAME: 'User last name',
    USER_LAST_NAME_EXAMPLE: 'Doe',
    USER_BIRTHDAY: 'User birthday',
    USER_BIRTHDAY_EXAMPLE: '1995-01-01',
    USER_AVATAR: 'User avatar',
    USER_AVATAR_EXAMPLE: 'https://example.com/avatar.jpg',
    REVIEW_SCORE_EXAMPLE: 5,
    REVIEW_COMMENT_EXAMPLE: 'Great vinyl!',
    VINYL_NAME: 'Vinyl name',
    VINYL_NAME_EXAMPLE: 'The Dark Side of the Moon',
    VINYL_AUTHOR: 'Vinyl author',
    VINYL_AUTHOR_EXAMPLE: 'Pink Floyd',
    VINYL_DESCRIPTION: 'A brief description of the vinyl.',
    VINYL_DESCRIPTION_EXAMPLE:
        'A progressive rock album by Pink Floyd, released in 1973.',
    VINYL_PRICE: 'Vinyl price',
    PRICE_EXAMPLE: 19.99,
    VINYL_COVER_IMAGE: 'Cover image URL',
    VINYL_COVER_IMAGE_EXAMPLE: 'https://example.com/cover-image.jpg',
    VINYL_AVG_SCORE: 'Average score',
    VINYL_AVG_SCORE_EXAMPLE: 4.5,
    VINYL_FIRST_REVIEW_COMMENT: 'First review comment',
    VINYL_FIRST_REVIEW_COMMENT_EXAMPLE: 'Great album!',
    VINYL_COUNT_EXAMPLE: 3,
    CHANGELOG_ENTITY_EXAMPLE: 'User',
    CHANGELOG_ACTION_TYPE_EXAMPLE: 'create',
    CHANGELOG_REFERENCE_ID_EXAMPLE: 123,
    CHANGELOG_OLD_VALUE_EXAMPLE: 'Old value',
    CHANGELOG_NEW_DATA_EXAMPLE: 'New value',
    CHANGELOG_CHANGE_DATE_EXAMPLE: '2021-01-01T00:00:00.000Z',
};
